INSERT INTO PRODUCT_DETAILS VALUES (1, 'Redmi Note-8 Pro', '8GB RAM, 16 GB Memory, 48MP Camera', 15000.00, '12 CM', 2, 1, 1);







INSERT INTO BRAND_DETAILS VALUES (1, 'Samsung');
INSERT INTO BRAND_DETAILS VALUES (2, 'Redmi');
INSERT INTO BRAND_DETAILS VALUES (3, 'Peter England');
INSERT INTO BRAND_DETAILS VALUES (4, 'Bufello');
INSERT INTO BRAND_DETAILS VALUES (5, 'Sony');
INSERT INTO BRAND_DETAILS VALUES (6, 'JBL');
INSERT INTO BRAND_DETAILS VALUES (7, 'HP');
INSERT INTO BRAND_DETAILS VALUES (8, 'Lenovo');

INSERT INTO CATEGORY_DETAILS VALUES (1, 'Mobile');
INSERT INTO CATEGORY_DETAILS VALUES (2, 'Shirt');
INSERT INTO CATEGORY_DETAILS VALUES (3, 'Pant');
INSERT INTO CATEGORY_DETAILS VALUES (4, 'Pendrive');
INSERT INTO CATEGORY_DETAILS VALUES (5, 'Headphone');
INSERT INTO CATEGORY_DETAILS VALUES (6, 'Laptop');

INSERT INTO COLOUR_DETAILS VALUES (1, 'White');
INSERT INTO COLOUR_DETAILS VALUES (2, 'Blue');
INSERT INTO COLOUR_DETAILS VALUES (3, 'Black');
INSERT INTO COLOUR_DETAILS VALUES (4, 'Purple');
INSERT INTO COLOUR_DETAILS VALUES (5, 'Orange');
INSERT INTO COLOUR_DETAILS VALUES (6, 'Silver');

INSERT INTO AVAILABLE_PRODUCT VALUES (100, 20);
INSERT INTO AVAILABLE_PRODUCT VALUES (101, 50);
INSERT INTO AVAILABLE_PRODUCT VALUES (102, 10);
INSERT INTO AVAILABLE_PRODUCT VALUES (103, 15);
INSERT INTO AVAILABLE_PRODUCT VALUES (104, 100);